# Generated by Django 5.2 on 2025-06-14 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
    ]
