# Generated by Django 5.2 on 2025-05-22 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_genre_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='genre_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music', to='core.genre'),
        ),
    ]
