# Generated by Django 5.2 on 2025-05-22 08:40

from django.db import migrations

def migrate_genre_data(apps, schema_editor):
    """
    Migrate data from genre text to genre_fk ForeignKey
    Create missing genres as needed
    """
    Music = apps.get_model('core', 'Music')
    Genre = apps.get_model('core', 'Genre')
    
    # Get all unique genre values
    genre_values = Music.objects.exclude(genre__isnull=True).exclude(genre='').values_list('genre', flat=True).distinct()
    
    # Create genres for any that don't exist
    for genre_name in genre_values:
        genre, created = Genre.objects.get_or_create(name=genre_name)
    
    # Update music items to use the genre_fk foreign key
    for music in Music.objects.exclude(genre__isnull=True).exclude(genre=''):
        try:
            genre = Genre.objects.get(name=music.genre)
            music.genre_fk = genre
            music.save()
        except Genre.DoesNotExist:
            # Skip if we can't find the genre (shouldn't happen)
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_music_genre_fk'),
    ]

    operations = [
        migrations.RunPython(migrate_genre_data, migrations.RunPython.noop),
    ]
